package gg.rsmod.plugins.content.combat.strategy.ranged.ammo

import gg.rsmod.plugins.api.cfg.Items

/**
 * @author Tom <rspsmods@gmail.com>
 */
object Knives {

    val BRONZE_KNIVES = arrayOf(Items.BRONZE_KNIFE, Items.BRONZE_KNIFEP, Items.BRONZE_KNIFEP_5654, Items.BRONZE_KNIFEP_5661)
    val IRON_KNIVES = arrayOf(Items.IRON_KNIFE, Items.IRON_KNIFEP, Items.IRON_KNIFEP_5655, Items.IRON_KNIFEP_5662)
    val STEEL_KNIVES = arrayOf(Items.STEEL_KNIFE, Items.STEEL_KNIFEP, Items.STEEL_KNIFEP_5656, Items.STEEL_KNIFEP_5663)
    val BLACK_KNIVES = arrayOf(Items.BLACK_KNIFE, Items.BLACK_KNIFEP, Items.BLACK_KNIFEP_5658, Items.BLACK_KNIFEP_5665)
    val MITHRIL_KNIVES = arrayOf(Items.MITHRIL_KNIFE, Items.MITHRIL_KNIFEP, Items.MITHRIL_KNIFEP_5657, Items.MITHRIL_KNIFEP_5664)
    val ADAMANT_KNIVES = arrayOf(Items.ADAMANT_KNIFE, Items.ADAMANT_KNIFEP, Items.ADAMANT_KNIFEP_5659, Items.ADAMANT_KNIFEP_5666)
    val RUNE_KNIVES = arrayOf(Items.RUNE_KNIFE, Items.RUNE_KNIFEP, Items.RUNE_KNIFEP_5660, Items.RUNE_KNIFEP_5667)
    val DRAGON_KNIVES = arrayOf(Items.DRAGON_KNIFE, Items.DRAGON_KNIFEP, Items.DRAGON_KNIFEP_22808, Items.DRAGON_KNIFEP_22810)

    val KNIVES = BRONZE_KNIVES + IRON_KNIVES + STEEL_KNIVES + BLACK_KNIVES + MITHRIL_KNIVES + ADAMANT_KNIVES + RUNE_KNIVES + DRAGON_KNIVES
}