package gg.rsmod.plugins.content.music

/**
 * ordinal tracks the client-side enum slot from 0 - 648
 */
enum class Songs(val title: String, val id: Int) {
    SCAPE_ORIGINAL("Scape Original", 400),
    SCAPE_MAIN("Scape Main", 0),
    GROUND_SCAPE("Scape Ground", 466),
    SCAPE_SCARED("Scape Scared", 321),
    SCAPE_SANTA("Scape Santa", 547),
    HARMONY("Harmony", 76),
    HARMONY2("Harmony 2", 46),
    THE_LOST_TRIBE("The Lost Tribe", 420),
    AUTUMN_VOYAGE("Autumn Voyage", 2),
    VENTURE("Venture", 75),
    VENTURE2("Venture 2", 45),
    BACKGROUND("Background", 324),
    CAMELOT("Camelot", 104),
    FLUTE_SALAD("Flute Salad", 163),
    DREAM("Dream", 327),
    BOOK_OF_SPELLS("Book of Spells", 64),
    DOORWAYS("Doorways", 56),
    SPIRIT("Spirit", 175),
    CELLAR_SONG("Cellar Song", 330),
    GREATNESS("Greatness", 116),
    ADVENTURE("Adventure", 177),
    SCAPE_WILD("Scape Wild", 332),
    WITCHING("Witching", 14),
    SCAPE_SAD("Scape Sad", 331),
    GARDEN("Garden", 125),
    EXPANSE("Expanse", 106),
    SCAPE_CAVE("Scape Cave", 144),
    PARADE("Parade", 93),
    MEDIEVAL("Medieval", 157),
    STILL_NIGHT("Still Night", 111),
    ARABIAN2("Arabian 2", 123),
    ARABIAN("Arabian", 36),
    AL_KHARID("Al Kharid", 50),
    FOREVER("Forever", 98),
    BARBARIANISM("Barbarianism", 141),
    SPOOKY("Spooky", 333),
    START("Start", 151),
    UNKNOWN_LAND("Unknown Land", 3),
    VISION("Vision", 85),
    SEA_SHANTY2("Sea Shanty 2", 35),
    FISHING("Fishing", 119),
    HIGH_SEAS("High Seas", 55),
    JUNGLE_ISLAND("Jungle Island", 172),
    SEA_SHANTY("Sea Shanty", 92),
    ARRIVAL("Arrival", 186),
    FANFARE("Fanfare", 72),
    MILES_AWAY("Miles Away", 107),
    LONG_WAY_HOME("Long Way Home", 12),
    WANDER("Wander", 49),
    ALONE("Alone", 102),
    GAOL("Gaol", 159),
    NIGHTFALL("Nightfall", 127),
    MAGICAL_JOURNEY("Magical Journey", 184),
    FRUITS_DE_MER("Fruits de Mer", 347),
    SPLENDOUR("Splendour", 77),
    ATTACK4("Attack 4", 27),
    ATTACK1("Attack 1", 24),
    DWARF_THEME("Dwarf Theme", 310),
    MELLOW("Mellow", 193),
    LIGHTWALK("Lightwalk", 74),
    THE_SHADOW("The Shadow", 170),
    WILDERNESS3("Wilderness 3", 43),
    WONDEROUS("Wonderous", 81),
    TRINITY("Trinity", 192),
    MARCH("March", 328),
    SAD_MEADOW("Sad Meadow", 5),
    KNIGHTLY("Knightly", 191),
    BAROQUE("Baroque", 99),
    BALLAD_OF_ENCHANTMENT("Ballad of Enchantment", 152),
    MONARCH_WALTZ("Monarch Waltz", 21),
    OVERTURE("Overture", 7),
    TALKING_FOREST("Talking Forest", 140),
    UPCOMING("Upcoming", 70),
    GNOME_KING("Gnome King", 22),
    GNOME_VILLAGE("Gnome Village", 33),
    JOLLYR("Jolly R", 6),
    NOMAD("Nomad", 58),
    SPOOKYJUNGLE("Spooky Jungle", 129),
    REGGAE("Reggae", 78),
    LONESOME("Lonesome", 168),
    TRIBAL_BACKGROUND("Tribal Background", 162),
    JUNGLY3("Jungly 3", 117),
    LANDLUBBER("Landlubber", 164),
    TRIBAL("Tribal", 165),
    REGGAE2("Reggae 2", 89),
    TRIBAL2("Tribal 2", 94),
    AMBIENT_JUNGLE("Ambient Jungle", 90),
    LULLABY("Lullaby", 20),
    WATERFALL("Waterfall", 82),
    VOYAGE("Voyage", 32),
    THE_TOWER("The Tower", 133),
    THEME("Theme", 109),
    LASTING("Lasting", 60),
    EMOTION("Emotion", 148),
    FANFARE3("Fanfare 3", 167),
    HORIZON("Horizon", 18),
    LEGION("Legion", 66),
    EGYPT("Egypt", 69),
    DESERT_VOYAGE("Desert Voyage", 174),
    ARABIAN3("Arabian 3", 124),
    NEVERLAND("Neverland", 155),
    MOODY("Moody", 10),
    SERENADE("Serenade", 110),
    LONG_AGO("Long Ago", 161),
    MAGIC_DANCE("Magic Dance", 185),
    GOBLIN_VILLAGE("Goblin Village", 313),
    INSPIRATION("Inspiration", 96),
    ARMY_OF_DARKNESS("Army of Darkness", 160),
    WILDWOOD("Wildwood", 8),
    WOLF_MOUNTAIN("Wolf Mountain", 189),
    UNDERCURRENT("Undercurrent", 176),
    ATTENTION("Attention", 180),
    BIG_CHORDS("Big Chords", 83),
    DANGEROUS("Dangerous", 182),
    EMPEROR("Emperor", 138),
    EXPECTING("Expecting", 41),
    GNOMEBALL("Gnomeball", 112),
    TREE_SPIRITS("Tree Spirits", 130),
    FAITHLESS("Faithless", 337),
    UNDERGROUND("Underground", 179),
    DARK("Dark", 326),
    SOUNDSCAPE("Soundscape", 80),
    IN_THE_MANOR("In the Manor", 188),
    CLOSE_QUARTERS("Close Quarters", 67),
    JUNGLY2("Jungly 2", 115),
    CRYSTAL_SWORD("Crystal Sword", 169),
    NEWBIE_MELODY("Newbie Melody", 62),
    WILDERNESS("Wilderness", 435),
    WONDER("Wonder", 34),
    TROUBLED("Troubled", 183),
    DEEP_WILDY("Deep Wildy", 37),
    WILDERNESS2("Wilderness 2", 42),
    JUNGLY1("Jungly 1", 114),
    FAERIE("Faerie", 118),
    CRYSTAL_CAVE("Crystal Cave", 181),
    ROYALE("Royale", 53),
    ATTACK6("Attack 6", 29),
    EXPEDITION("Expedition", 153),
    ATTACK2("Attack 2", 25),
    ATTACK5("Attack 5", 28),
    ARABIQUE("Arabique", 19),
    DUNJUN("Dunjun", 173),
    WOE_OF_THE_WYVERN("Woe of the Wyvern", 529),
    STARLIGHT("Starlight", 108),
    ORIENTAL("Oriental", 103),
    CAVE_BACKGROUND("Cave Background", 325),
    ATTACK3("Attack 3", 26),
    COURAGE("Courage", 178),
    RUNE_ESSENCE("Rune Essence", 57),
    TRAWLER("Trawler", 38),
    TRAWLER_MINOR("Trawler Minor", 51),
    UPASS("Underground Pass", 323),
    CURSED("Cursed", 59),
    INTREPID("Intrepid", 95),
    VOODOO_CULT("Voodoo Cult", 30),
    SUPERSTITION("Superstition", 265),
    IBAN("Iban", 1),
    CHAIN_OF_COMMAND("Chain of Command", 63),
    REGAL("Regal", 329),
    THE_DESERT("The Desert", 79),
    GNOME_VILLAGE2("Gnome Village 2", 101),
    BEYOND("Beyond", 100),
    WORKSHOP("Workshop", 15),
    NARNODES_THEME("Narnode's Theme", 348),
    GOBLIN_GAME("Goblin Game", 346),
    ESCAPE("Escape", 17),
    MAGE_ARENA("Mage Arena", 13),
    COMPLICATION("Complication", 142),
    HEART_AND_MIND("Heart and Mind", 190),
    ZEALOT("Zealot", 146),
    SERENE("Serene", 52),
    CAVERN("Cavern", 68),
    MIRACLE_DANCE("Miracle Dance", 65),
    QUEST("Quest", 158),
    SCAPE_SOFT("Scape Soft", 54),
    SHINING("Shining", 120),
    YESTERYEAR("Yesteryear", 145),
    FANFARE2("Fanfare 2", 166),
    DUEL_ARENA("Duel Arena", 47),
    SHADOWLAND("Shadowland", 286),
    SHINE("Shine", 122),
    ICE_MELODY("Ice Melody", 87),
    GRUMPY("Grumpy", 128),
    CHOMPY_HUNT("Chompy Hunt", 71),
    TWILIGHT("Twilight", 88),
    MORYTANIA("Morytania", 48),
    DEAD_QUIET("Dead Quiet", 84),
    VILLAGE("Village", 61),
    BONE_DANCE("Bone Dance", 154),
    MAUSOLEUM("Mausoleum", 156),
    FORBIDDEN("Forbidden", 121),
    UNDERSTANDING("Understanding", 131),
    PRINCIPALITY("Principality", 149),
    TREMBLE("Tremble", 187),
    HERMIT("Hermit", 97),
    LA_MORT("La Mort", 134),
    STAGNANT("Stagnant", 241),
    BREEZE("Breeze", 132),
    STRATOSPHERE("Stratosphere", 243),
    TIME_OUT("Time Out", 242),
    NATURAL("Natural", 245),
    GROTTO("Grotto", 246),
    WATERLOGGED("Waterlogged", 244),
    ARTISTRY("Artistry", 247),
    AZTEC("Aztec", 248),
    ELVEN_MIST("Elven Mist", 252),
    FOREST("Forest", 251),
    LOST_SOUL("Lost Soul", 253),
    MERIDIAN("Meridian", 254),
    WOODLAND("Woodland", 255),
    OVERPASS("Overpass", 256),
    CONTEST("Contest", 258),
    SOJOURN("Sojourn", 257),
    CRYSTAL_CASTLE("Crystal Castle", 259),
    MARZIPAN("Marzipan", 261),
    INSECT_QUEEN("Insect Queen", 260),
    MAD_EADGAR("Mad Eadgar", 264),
    BANDIT_CAMP("Bandit Camp", 263),
    SUNBURN("Sunburn", 267),
    BONE_DRY("Bone Dry", 266),
    COMPETITION("Competition", 269),
    EVERYWHERE("Everywhere", 268),
    EXPOSED("Exposed", 270),
    RIVERSIDE("Riverside", 91),
    WELL_OF_VOYAGE("Well of Voyage", 271),
    RIGHTEOUSNESS("Righteousness", 262),
    DOWN_TO_EARTH("Down to Earth", 143),
    HAUNTED_MINE("Haunted Mine", 277),
    SPOOKY2("Spooky 2", 11),
    DEEP_DOWN("Deep Down", 278),
    CHAMBER("Chamber", 282),
    MISCELLANIA("Miscellania", 284),
    ETCETERA("Etceteria", 285),
    LAIR("Lair", 287),
    DEADLANDS("Deadlands", 288),
    RELLEKKA("Rellekka", 289),
    SAGA("Saga", 290),
    BORDERLAND("Borderland", 291),
    LEGEND("Legend", 293),
    WARRIOR("Warrior", 295),
    THE_NAVIGATOR("The Navigator", 316),
    TECHNOLOGY("Technology", 296),
    MONKEY_MADNESS("Monkey Madness", 303),
    ANYWHERE("Anywhere", 305),
    MAROONED("Marooned", 304),
    ISLAND_LIFE("Island Life", 306),
    TEMPLE("Temple", 307),
    SUSPICIOUS("Suspicious", 308),
    SHOWDOWN("Showdown", 311),
    FIND_MY_WAY("Find My Way", 312),
    CASTLEWARS("Castle Wars", 314),
    MELODRAMA("Melodrama", 317),
    READY_FOR_BATTLE("Ready for Battle", 318),
    LIGHTHOUSE("Lighthouse", 320),
    OUT_OF_THE_DEEP("Out of the Deep", 322),
    HELLS_BELLS("Hells Bells", 4),
    PIRATES_OF_PERIL("Pirates of Peril", 334),
    DANGEROUS_ROAD("Dangerous Road", 336),
    ROMANCING_THE_CRONE("Romancing the Crone", 335),
    STRANDED("Stranded", 292),
    STILLNESS("Stillness", 319),
    SEVENTH_REALM("7th Realm", 363),
    KARAMJA_JAM("Karamja Jam", 362),
    PATHWAYS("Pathways", 364),
    THE_TERRIBLE_TOWER("The Terrible Tower", 339),
    MASQUERADE("Masquerade", 340),
    THE_SLAYER("The Slayer", 341),
    BODY_PARTS("Body Parts", 342),
    FENKENSTRAINS_REFRAIN("Fenkenstrain's Refrain", 344),
    BARKING_MAD("Barking Mad", 345),
    SHIPWRECKED("Shipwrecked", 353),
    PHASMATYS("Phasmatys", 354),
    THE_OTHER_SIDE("The Other Side", 355),
    DRAGONTOOTH_ISLAND("Dragontooth Island", 358),
    MONSTER_MELEE("Monster Melee", 343),
    SETTLEMENT("Settlement", 356),
    CAVE_OF_BEASTS("Cave of Beasts", 357),
    CAVE_OF_THE_GOBLINS("Cave of the Goblins", 389),
    LAND_OF_THE_DWARVES("Land of the Dwarves", 396),
    TALE_OF_KELDAGRIM("Tale of Keldagrim", 395),
    TIME_TO_MINE("Time to Mine", 369),
    IN_BETWEEN("In Between", 370),
    CLAUSTROPHOBIA("Claustrophobia", 373),
    DYNASTY("Dynasty", 351),
    THE_GOLEM("The Golem", 377),
    THRONE_OF_THE_DEMON("Throne of the Demon", 379),
    FORGOTTEN("Forgotten", 378),
    INCANTATION("Incantation", 519),
    GRIP_OF_THE_TALON("Grip of the Talon", 520),
    FROSTBITE("Frostbite", 294),
    SCARAB("Scarab", 352),
    SARCOPHAGUS("Sarcophagus", 359),
    PATH_OF_PERIL("Path of Peril", 393),
    DOWN_BELOW("Down Below", 361),
    CITY_OF_THE_DEAD("City of the Dead", 383),
    SPHINX("Sphinx", 387),
    HYPNOTIZED("Hypnotized", 384),
    MIRAGE("Mirage", 388),
    TEARS_OF_GUTHIX("Tears of Guthix", 397),
    THE_POWER_OF_TEARS("The Power of Tears", 398),
    DANCE_OF_THE_UNDEAD("Dance of the Undead", 380),
    DANGEROUS_WAY("Dangerous Way", 381),
    ZOGRE_DANCE("Zogre Dance", 392),
    WAYWARD("Wayward", 394),
    ROMPER_CHOMPER("Romper Chomper", 390),
    THE_LOST_MELODY("The Lost Melody", 407),
    INTO_THE_ABYSS("Into the Abyss", 412),
    THE_ROGUES_DEN("The Rogues' Den", 402),
    THE_FAR_SIDE("The Far Side", 403),
    THE_CHOSEN("The Chosen", 425),
    FAR_AWAY("Far Away", 372),
    FIGHT_OR_FLIGHT("Fight or Flight", 375),
    FORGETTABLE_MELODY("Forgettable Melody", 436),
    RIGHT_ON_TRACK("Right on Track", 44),
    THE_MONSTERS_BELOW("The Monsters Below", 448),
    THE_DESOLATE_ISLE("The Desolate Isle", 461),
    EVIL_BOBS_ISLAND("Evil Bob's Island", 411),
    PHEASANT_PEASANT("Pheasant Peasant", 419),
    FROGLAND("Frogland", 409),
    THE_QUIZMASTER("The Quizmaster", 413),
    BREW_HOO_HOO("Brew Hoo Hoo!", 471),
    WILD_SIDE("Wild Side", 475),
    LIGHTNESS("Lightness", 113),
    DEAD_CAN_DANCE("Dead Can Dance", 476),
    THE_CELLAR_DWELLERS("The Cellar Dwellers", 478),
    JUNGLE_TROUBLES("Jungle Troubles", 479),
    HAVE_A_BLAST("Have a Blast", 434),
    FIRE_AND_BRIMSTONE("Fire and Brimstone", 463),
    IN_THE_PITS("In the Pits", 469),
    TZHAAR("TzHaar!", 473),
    STRANGE_PLACE("Strange Place", 470),
    TEMPLE_OF_LIGHT("Temple of Light", 376),
    CORPORAL_PUNISHMENT("Corporal Punishment", 418),
    MUDSKIPPER_MELODY("Mudskipper Melody", 515),
    AYE_CAR_RUM_BA("Aye Car Rum Ba", 497),
    BLISTERING_BARNACLES("Blistering Barnacles", 498),
    SUBTERRANEA("Subterranea", 517),
    DAGANNOTH_DAWN("Dagannoth Dawn", 198),
    XENOPHOBE("Xenophobe", 524),
    RAT_HUNT("Rat Hunt", 491),
    RAT_A_TAT_TAT("Rat a Tat Tat", 482),
    THE_NOBLE_RODENT("The Noble Rodent", 485),
    BUBBLE_AND_SQUEAK("Bubble and Squeak", 489),
    SARIMS_VERMIN("Sarim's Vermin", 490),
    CATCH_ME_IF_YOU_CAN("Catch Me If You Can", 481),
    OVER_TO_NARDAH("Over to Nardah", 447),
    SPIRITS_OF_ELID("Spirits of the Elid", 462),
    THE_GENIE("The Genie", 464),
    DESERT_HEAT("Desert Heat", 465),
    TITLE_FIGHT("Title Fight", 525),
    VICTORY_IS_MINE("Victory is Mine", 528),
    DIANGOS_LITTLE_HELPERS("Diango's Little Helpers", 532),
    THE_ENCHANTER("The Enchanter", 541),
    ROLL_THE_BONES("Roll the Bones", 533),
    GOLDEN_TOUCH("Golden Touch", 535),
    MIND_OVER_MATTER("Mind over Matter", 534),
    IN_THE_CLINK("In the Clink", 511),
    TIPTOE("Tiptoe", 338),
    SCAPE_HUNTER("Scape Hunter", 207),
    EAGLE_PEAK("Eagles' Peak", 366),
    WHERE_EAGLES_LAIR("Where Eagles Lair", 620),
    POLES_APART("Poles Apart", 548),
    JUNGLE_HUNT("Jungle Hunt", 453),
    JOY_OF_THE_HUNT("Joy of the Hunt", 460),
    ON_THE_WING("On the Wing", 633),
    DISTANT_LAND("Distant Land", 501),
    FANGS_FOR_THE_MEMORY("Fangs for the Memory", 504),
    PHAROAHS_TOMB("Pharaoh's Tomb", 505),
    LAND_DOWN_UNDER("Land Down Under", 506),
    MEDDLING_KIDS("Meddling Kids", 508),
    CORRIDORS_OF_POWER("Corridors of Power", 509),
    SLITHER_AND_THITHER("Slither and Thither", 510),
    IN_THE_BRINE("In the Brine", 530),
    CABIN_FEVER("Cabin Fever", 545),
    MAKING_WAVES("Making Waves", 544),
    LAST_STAND("Last Stand", 546),
    LAMENT("Lament", 542),
    HOME_SWEET_HOME("Home Sweet Home", 454),
    HOMESCAPE("Scape Home", 621),
    DOGS_OF_WAR("Dogs of War", 537),
    FOOD_FOR_THOUGHT("Food for Thought", 558),
    MALADY("Malady", 559),
    DANCE_OF_DEATH("Dance of Death", 560),
    STORM_BREW("Storm Brew", 568),
    WRATH_AND_RUIN("Wrath and Ruin", 565),
    NO_WAY_OUT("No Way Out", 594),
    METHOD_OF_MADNESS("Method of Madness", 600),
    FEAR_AND_LOATHING("Fear and Loathing", 602),
    THE_MAD_MOLE("The Mad Mole", 573),
    DAVY_JONES_LOCKER("Davy Jones' Locker", 576),
    CHICKENED_OUT("Chickened Out", 575),
    MASTERMINDLESS("Mastermindless", 577),
    TOO_MANY_COOKS("Too Many Cooks...", 386),
    CHEF_SURPRIZE("Chef Surprise", 583),
    NULL_AND_VOID("Null and Void", 587),
    PEST_CONTROL("Pest Control", 588),
    TOMB_RAIDER("Tomb Raider", 591),
    FUNNY_BUNNIES("Funny Bunnies", 603),
    EVERLASTING_FIRE("Everlasting Fire", 586),
    DISTILLERY_HILARITY("Distillery Hilarity", 610),
    TROUBLE_BREWING("Trouble Brewing", 611),
    HEAD_TO_HEAD("Head to Head", 612),
    PINBALL_WIZARD("Pinball Wizard", 614),
    LIFES_A_BEACH("Life's a Beach!", 631),
    LITTLE_CAVE_OF_HORRORS("Little Cave of Horrors", 632),
    THE_DEPTHS("The Depths", 606),
    LABYRINTH("Labyrinth", 213),
    BEETLE_JUICE("Beetle Juice", 615),
    BACK_TO_LIFE("Back to Life", 616),
    WAKING_DREAM("Waking Dream", 622),
    DREAMSTATE("Dreamstate", 623),
    THE_LUNAR_ISLE("The Lunar Isle", 625),
    ISLE_OF_EVERYWHERE("Isle of Everywhere", 627),
    WAY_OF_THE_ENCHANTER("Way of the Enchanter", 626),
    THE_GALLEON("The Galleon", 630),
    WARRIORS_GUILD("Warriors' Guild", 634),
    KINGDOM("Kingdom", 9),
    TOMORROW("Tomorrow", 105),
    HAM_FISTED("H.A.M. Fisted", 638),
    SIGMUNDS_SHOWDOWN("Sigmund's Showdown", 640),
    WE_ARE_THE_FAIRIES("We are the Fairies", 126),
    DIMENSION_X("Dimension X", 86),
    ALLS_FAIRY_IN_LOVE_N_WAR("All's Fairy in Love & War", 73),
    BRIMSTAILS_SCALES("Brimstail's Scales", 194),
    LAMENT_OF_MEIYERDITCH("Lament of Meiyerditch", 197),
    THE_LAST_SHANTY("The Last Shanty", 643),
    NIGHT_OF_THE_VAMPIYRE("Night of the Vampyre", 646),
    MY_ARMS_JOURNEY("My Arm's Journey", 203),
    ROC_AND_ROLL("Roc and Roll", 204),
    THE_MOLLUSC_MENACE("The Mollusc Menace", 200),
    SLUG_A_BUG_BALL("Slug a Bug Ball", 201),
    PRIME_TIME("Prime Time", 202),
    FLOATING_FREE("Floating Free", 206),
    HIGH_SPIRITS("High Spirits", 205),
    MAJOR_MINER("Major Miner", 222),
    JESTER_MINUTE("Jester Minute", 221),
    NORSE_CODE("Norse Code", 223),
    VOLCANIC_VIKINGS("Volcanic Vikings", 225),
    ISLAND_OF_THE_TROLLS("Island of the Trolls", 220),
    OGRE_THE_TOP("Ogre the Top", 224),
    RISING_DAMP("Rising Damp", 274),
    WORK_WORK_WORK("Work, Work, Work", 237),
    MAGIC_MAGIC_MAGIC("Magic, Magic, Magic", 235),
    CREATURE_CRUELTY("Creature Cruelty", 234),
    MUTANT_MEDLEY("Mutant Medley", 236),
    DORGESHUN_CITY("Dorgeshuun City", 240),
    DORGESHUN_DEEP("Dorgeshuun Deep", 249),
    ASSAULT_AND_BATTERY("Assault and Battery", 604),
    PIRATES_OF_PENANCE("Pirates of Penance", 211),
    JUNGLE_ISLAND_XMAS("Jungle Island Xmas", 208),
    SEA_SHANTY_XMAS("Sea Shanty Xmas", 210),
    JUNGLE_BELLS("Jungle Bells", 209),
    GARDEN_OF_SPRING("Garden of Spring", 229),
    GARDEN_OF_SUMMER("Garden of Summer", 230),
    GARDEN_OF_AUTUMN("Garden of Autumn", 228),
    GARDEN_OF_WINTER("Garden of Winter", 231),
    HAVE_AN_ICE_DAY("Have an Ice Day", 217),
    ESPIONAGE("Espionage", 216),
    ZOMBIISM("Zombiism", 238),
    ALTERNATIVE_ROOT("Alternative Root", 272),
    UNDEAD_DUNGEON("Undead Dungeon", 214),
    EASTER_JIG("Easter Jig", 273),
    HAM_ATTACK("H.A.M. Attack", 279),
    SLICE_OF_SILENT_MOVIE("Slice of Silent Movie", 281),
    HAM_AND_SEEK("H.A.M. and Seek", 276),
    SLICE_OF_STATION("Slice of Station", 275),
    LOOKING_BACK("Looking Back", 309),
    BARB_WIRE("Barb Wire", 367),
    IMPETUOUS("Impetuous", 349),
    SCHOOLS_OUT("School's Out", 371),
    DOWN_AND_OUT("Down and Out", 301),
    ON_THE_UP("On the Up", 302),
    INADEQUACY("Inadequacy", 299),
    ILLUSIVE("Illusive", 298),
    EVERLASTING("Everlasting", 283),
    UNTOUCHABLE("Untouchable", 300),
    MOUSE_TRAP("Mouse Trap", 150),
    FE_FI_FO_FUM("Fe Fi Fo Fum", 23),
    MELZARS_MAZE("The Maze", 365),
    KNIGHTMARE("Knightmare", 374),
    LORE_AND_ORDER("Lore and Order", 382),
    ARMAGEDDON("Armageddon", 404),
    ARMADYL_ALLIANCE("Armadyl Alliance", 414),
    BANDOS_BATTALION("Bandos Battalion", 408),
    STRENGTH_OF_SARADOMIN("Strength of Saradomin", 391),
    ZAMORAK_ZOO("Zamorak Zoo", 399),
    GNOME_VILLAGE_PARTY("Gnome Village Party", 416),
    BENEATH_THE_STRONGHOLD("Beneath the Stronghold", 417),
    TROUBLED_WATERS("Troubled Waters", 421),
    NETHER_REALM("Nether Realm", 422),
    SCORPIA_DANCES("Scorpia Dances", 423),
    DEVILS_MAY_CARE("Devils May Care", 424),
    PICK_AND_SHOVEL("Pick & Shovel", 426),
    CLANWARS("Clan Wars", 428),
    WARPATH("Warpath", 427),
    CORPOREALBEAST("Bane", 430),
    GRIMLY_FIENDISH("Grimly Fiendish", 431),
    SHINING_SPIRIT("Shining Spirit", 429),
    COIL("Coil", 432),
    THRALL_OF_THE_SERPENT("Thrall of the Serpent", 433),
    THE_TRADE_PARADE("The Trade Parade", 496),
    BUNNY_SUGAR_RUSH("Bunny's Sugar Rush", 437),
    MAWS_JAWS_CLAWS("Maws, Jaws & Claws", 439),
    THAT_SULLEN_HALL("That Sullen Hall", 440),
    SIRE("Invader", 441),
    DIES_IRAE("Dies Irae", 442),
    NOX_IRAE("Nox Irae", 443),
    KOUREND_THE_MAGNIFICENT("Kourend the Magnificent", 451),
    ZEAH_FISHING("Down by the Docks", 450),
    ZEAH_MAGIC("Arcane", 455),
    ZEAH_COMBAT("The Militia", 449),
    ZEAH_MINING("Dwarven Domain", 446),
    ZEAH_FARMING("Country Jig", 456),
    FORLORN_HOMESTEAD("The Forlorn Homestead", 452),
    SOULFALL("Soul Fall", 444),
    RUGGED_TERRAIN("Rugged Terrain", 445),
    MONKEY_TROUBLE("Monkey Trouble", 457),
    MONKEY_SADNESS("Monkey Sadness", 459),
    MONKEY_BUSINESS("Monkey Business", 467),
    MONKEY_BADNESS("Monkey Badness", 468),
    SCAPE_APE("Scape Ape", 458),
    DARKLY_ALTARED("Darkly Altared", 472),
    LAST_MAN_STANDING("Last Man Standing", 474),
    WASTELAND("The Doors of Dinh", 477),
    WINTERTODT_BOSS("Ice and Fire", 483),
    ALTAR_EGO("Altar Ego", 486),
    SHAYZIEN_MARCH("March of the Shayzien", 488),
    LOWER_DEPTHS("Lower Depths", 487),
    DESOLATE_MAGE("The Desolate Mage", 495),
    OLM_BATTLE("Fire in the Deep", 493),
    UPPER_DEPTHS("Upper Depths", 492),
    ASCENT("Ascent", 494),
    DARKNESS_IN_THE_DEPTHS("Darkness in the Depths", 499),
    INFERNO("Inferno", 500),
    MOR_UL_REK("Mor Ul Rek", 502),
    LAGOON("Lagoon", 503), // key not known
    LAVAISMINE("Lava is Mine", 507), // key not known
    FOSSILISED("Fossilised", 514), // key not known
    PRESERVED("Preserved", 513), // key not known
    PRESERVATION("Preservation", 512), // key not known
    GARGOYLEBOSS("Tempest", 518),
    REVENANTS("Revenants", 521),
    ON_THE_SHORE("On the Shore", 522),
    LAND_OF_SNOW("Land of Snow", 523),
    WINTER_FUNFARE("Winter Funfair", 526),
    DRAGONKIN_TEMPLE("Relics", 549),
    DRAGONSLAYER("The Dragon Slayer", 543), // key not known
    MYTHS_GUILD("Mythical", 550),
    ZOMBIE_DRAGON("On Thin Ice", 536),
    SHAYZIEN_CRYPT("The Walking Dead", 551),
    DRAGONKIN_AMBIENCE("The Forsaken", 527),
    ONCOMING_FOE("Oncoming Foe", 540),
    LUCID_DREAM("Lucid Dream", 539),
    LUCID_NIGHTMARE("Lucid Nightmare", 531),
    MUSEUMMEDLEY("Museum Medley", 553), // key not known
    SCAPEFIVE("Scape Five", 552), // key not known
    ROOTS_AND_FLUTES("Roots and Flutes", 554),
    CONSPIRACY("Conspiracy", 561),
    BAIT("Bait", 563),
    VANESCULA("Vanescula", 562),
    BLOODBATH("Bloodbath", 557),
    WELCOMETOTHEATRE("Welcome to the Theatre", 556), // key not known
    ATASTEOFHOPE("A Taste of Hope", 555), // key not known
    MAIDEN_AMBIENCE("The Maiden's Sorrow", 570),
    MAIDEN_COMBAT("The Maiden's Anger", 569),
    PESTILENT_BLOAT_AMBIENCE("Welcome to my Nightmare", 578),
    PESTILENT_BLOAT_COMBAT("The Nightmare Continues", 571),
    SOTETSEG_AMBIENCE("The Dark Beast Sotetseg", 584),
    SOTETSEG_COMBAT("Power of the Shadow Realm", 581),
    VERZIK_AMBIENCE("It's not over 'til...", 566),
    VERZIK_COMBAT("The Fat Lady Sings", 572),
    VERZIK_DEFEATED("The Curtain Closes", 582),
    NYLOCAS_AMBIENCE("Dance of the Nylocas", 580),
    NYLOCAS_COMBAT("Arachnids of Vampyrium", 579),
    XARPUS_AMBIENCE("Predator Xarpus", 567),
    XARPUS_COMBAT("Last King of the Yarasa", 564),
    BARREN_LAND("Barren Land", 585),
    WEISS_TOWN("Lumbering", 590),
    TROLL_SHUFFLE("Troll Shuffle", 592),
    MY2ARM_LOVE_THEME_FULL("Snowflake & My Arm", 589),
    MY2ARM_BOSS_BATTLE("Mother Ruckus", 593),
    GILL_BILL("Gill Bill", 618),
    WAY_OF_THE_WYRM("Way of the Wyrm", 595),
    KANONOFKAHLITH("Kanon of Kahlith", 608), // key not known
    FUL_TO_THE_BRIM("Ful to the Brim", 635),
    HOE_DOWN("Hoe Down", 599),
    WOODLAND_WALK("A Walk in the Woods", 636),
    BURNING_DESIRE("Burning Desire", 629),
    ALCHEMICAL_HYDRA("Alchemical Attack!", 598),
    STUCK_IN_THE_MIRE("Stuck in the Mire", 607),
    NEWBIE_FARMING("Newbie Farming", 597),
    A_FARMERS_GRIND("A Farmer's Grind", 609),
    GETTING_DOWN_TO_BUSINESS("Getting Down to Business", 617),
    GROW_GROW_GROW("Grow Grow Grow", 613),
    HESPORI("A Thorn in My Side", 601),
    FORSAKEN_TOWER("The Forsaken Tower", 624),
    BATTLEFRONT("On the Frontline", 605),
    MOLCH("Servants of Strife", 628),
    HESPORI_CAVE("Creeping Vines", 596),
    BOX_OF_DELIGHTS("Box of Delights", 637),
    FORTHOS_DUNGEON("A Forgotten Religion", 639),
    SARACHNIS_LAIR("Sarachnis", 641),
    ELVEN_SEED("Elven Seed", 654),
    FAITH_OF_THE_HEFIN("Faith of the Hefin", 653),
    THE_TOWER_OF_VOICES("The Tower of Voices", 648),
    DANCE_OF_THE_MEILYR("Dance of the Meilyr", 660),
    IOWERTHS_LAMENT("Iorwerth's Lament", 644),
    AMLODD("Mystics of Nature", 655),
    CRYWS("The Seed of Crwys", 659),
    ITHELL("Architects of Prifddinas", 651),
    TRAHAEARNTOIL("Trahaearn Toil", 649), // key not known
    GAUNTLET_MINIGAME("The Gauntlet", 650),
    ZALCANO_COMBAT("The Spurned Demon", 662),
    PRIF_SLAYER_DUNGEON("Sharp End of the Crystal", 657),
    SCAPE_CRYSTAL("Scape Crystal", 661),
    WARPED_LIBRARY("Song of the Elves", 645),
    CITY_GUARDIANS("Elven Guardians", 647),
    FIRESOFLLETYA("The Fires of Lletya", 658), // key not known
    STAND_UP_AND_BE_COUNTED("Stand Up and Be Counted", 656),
    NO_PASARAN("No Pasaran", 642),
    THE_DARK_FRAGMENT("The Fragment", 652),
    JAWS_OF_THE_BASILISK("Jaws of the Basilisk", 135),
    LAIR_OF_THE_BASILISK("Lair of the Basilisk", 136),
    FIGHT_OF_THE_BASILISK("Fight of the Basilisk", 31),
    JORMUNGAND_FIGHT("Reign of the Basilisk", 199),
    BALLAD_OF_THE_BASILISK("Ballad of the Basilisk", 139),
    ARBORETUM("Arboretum", 670),
    DARKMEYER("Darkmeyer", 671),
    UPIR_LIKHYI("Upir Likhyi", 672),
    THE_TERRIBLE_CAVERNS("The Terrible Caverns", 667),
    THE_TERRIBLE_TUNNELS("The Terrible Tunnels", 675),
    NIGHTMARE_COMBAT("The Bane of Ashihama", 663),
    SLEPE_DUNGEON("The Everlasting Slumber", 664),
    DOMAIN_OF_THE_VAMPYRES("Domain of the Vampyres", 677),
    LAMENTFORHALLOWED("Lament for the Hallowed", 665), // key not known
    WELL_HALLOWED_AIR("Well Hallowed Air", 669),
    MORYTANIANMYSTERY("Morytanian Mystery", 676), // key not known
    VANSTROM("Vampyre Assault", 678),
    YOUHAVEMYATTENTION("You Have My Attention", 666), // key not known
    HALLOWED_SEPULCHRE("Watch Your Step", 674),
    REST_IN_PEACE("Rest in Peace", 679),
    THE_ENCLAVE("The Enclave", 680),
    SAFETY_IN_NUMBERS("Safety in Numbers", 681),
    EVES_EPINETTE("Eve's Epinette", 682),
    SEA_MINOR_SHANTY("Sea Minor Shanty", 683),
    ADANGEROUSGAME("A Dangerous Game", -1),
    SCRUBFOOTS_DESCENT("Scrubfoot's Descent", 687),
    THE_WAITING_GAME("The Waiting Game", 686),
    SOUL_WARS("Soul Wars", 685),
    ;

    companion object{
        val values = values()

        fun getTitle(id: Int): String {
            values.forEach { song ->
                if (song.id == id) return song.title
            }
            return "";
        }
    }
}