package gg.rsmod.plugins.content.combat.strategy.ranged.ammo

import gg.rsmod.plugins.api.cfg.Items

/**
 * @author Tom <rspsmods@gmail.com>
 */
object Arrows {

    val TRAINING_ARROWS = arrayOf(Items.TRAINING_ARROWS)
    val OGRE_ARROWS = arrayOf(Items.OGRE_ARROW)

    val BRONZE_ARROWS = arrayOf(Items.BRONZE_ARROW, Items.BRONZE_ARROWP, Items.BRONZE_ARROWP_5616, Items.BRONZE_ARROWP_5622)
    val IRON_ARROWS = arrayOf(Items.IRON_ARROW, Items.IRON_ARROWP, Items.IRON_ARROWP_5617, Items.IRON_ARROWP_5623)
    val STEEL_ARROWS = arrayOf(Items.STEEL_ARROW, Items.STEEL_ARROWP, Items.STEEL_ARROWP_5618, Items.STEEL_ARROWP_5624)
    val MITHRIL_ARROWS = arrayOf(Items.MITHRIL_ARROW, Items.MITHRIL_ARROWP, Items.MITHRIL_ARROWP_5619, Items.MITHRIL_ARROWP_5625)
    val ADAMANT_ARROWS = arrayOf(Items.ADAMANT_ARROW, Items.ADAMANT_ARROWP, Items.ADAMANT_ARROWP_5620, Items.ADAMANT_ARROWP_5626)
    val RUNE_ARROWS = arrayOf(Items.RUNE_ARROW, Items.RUNE_ARROWP, Items.RUNE_ARROWP_5621, Items.RUNE_ARROWP_5627)
    val AMETHYST_ARROWS = arrayOf(Items.AMETHYST_ARROW, Items.AMETHYST_ARROWP, Items.AMETHYST_ARROWP_21334, Items.AMETHYST_ARROWP_21336)
    val DRAGON_ARROWS = arrayOf(Items.DRAGON_ARROW, Items.DRAGON_ARROWP, Items.DRAGON_ARROWP_11228, Items.DRAGON_ARROWP_11229)

    val BRUTAL_BRONZE_ARROWS = arrayOf(Items.BRONZE_BRUTAL)
    val BRUTAL_IRON_ARROWS = arrayOf(Items.IRON_BRUTAL)
    val BRUTAL_STEEL_ARROWS = arrayOf(Items.STEEL_BRUTAL)
    val BRUTAL_BLACK_ARROWS = arrayOf(Items.BLACK_BRUTAL)
    val BRUTAL_MITHRIL_ARROWS = arrayOf(Items.MITHRIL_BRUTAL)
    val BRUTAL_ADAMANT_ARROWS = arrayOf(Items.ADAMANT_BRUTAL)
    val BRUTAL_RUNE_ARROWS = arrayOf(Items.RUNE_BRUTAL)
}