package gg.rsmod.plugins.content.combat.strategy.ranged.ammo

import gg.rsmod.plugins.api.cfg.Items

/**
 * @author Tom <rspsmods@gmail.com>
 */
object Javelins {

    val BRONZE_JAVELINS = arrayOf(Items.BRONZE_JAVELIN, Items.BRONZE_JAVELINP, Items.BRONZE_JAVELINP_5642, Items.BRONZE_JAVELINP_5648)
    val IRON_JAVELINS = arrayOf(Items.IRON_JAVELIN, Items.IRON_JAVELINP, Items.IRON_JAVELINP_5643, Items.IRON_JAVELINP_5649)
    val STEEL_JAVELINS = arrayOf(Items.STEEL_JAVELIN, Items.STEEL_JAVELINP, Items.STEEL_JAVELINP_5644, Items.STEEL_JAVELINP_5650)
    val MITHRIL_JAVELINS = arrayOf(Items.MITHRIL_JAVELIN, Items.MITHRIL_JAVELINP, Items.MITHRIL_JAVELINP_5645, Items.MITHRIL_JAVELINP_5651)
    val ADAMANT_JAVELINS = arrayOf(Items.ADAMANT_JAVELIN, Items.ADAMANT_JAVELINP, Items.ADAMANT_JAVELINP_5646, Items.ADAMANT_JAVELINP_5652)
    val RUNE_JAVELINS = arrayOf(Items.RUNE_JAVELIN, Items.RUNE_JAVELINP, Items.RUNE_JAVELINP_5647, Items.RUNE_JAVELINP_5653)
    val AMETHYST_JAVELINS = arrayOf(Items.AMETHYST_JAVELIN, Items.AMETHYST_JAVELINP, Items.AMETHYST_JAVELINP_21322, Items.AMETHYST_JAVELINP_21324)
    val DRAGON_JAVELINS = arrayOf(Items.DRAGON_JAVELIN, Items.DRAGON_JAVELINP, Items.DRAGON_JAVELINP_19488, Items.DRAGON_JAVELINP_19490)
}